name: MergeChecks
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  EslintValidation:
    name: Validate eslint rules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          yarn install
      - name: Run eslint validation
        run: npm run lint

  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install testing dependencies
        run: |
          yarn install
      - name: Run unit tests
        run: npm test
